packages:
  - apps/*
  - packages/*

catalogs:
  default:
    '@eslint/js': ^9.39.1
    '@hono/node-server': ^1.19.9
    '@hono/standard-validator': ^v0.2.2
    '@hono/zod-openapi': ^1.2.2
    '@hono/zod-validator': ^0.7.6
    '@hookform/resolvers': ^5.2.2
    '@scalar/hono-api-reference': ^0.9.41
    '@tailwindcss/vite': ^4.1.18
    '@tanstack/react-query': ^5.90.21
    '@types/node': ^20.11.17
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    '@types/uuid': ^11.0.0
    '@vitejs/plugin-react': ^5.1.1
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    drizzle-kit: ^0.31.9
    drizzle-orm: ^0.45.1
    eslint: ^9.39.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.20
    globals: ^16.5.0
    hono: ^4.11.9
    hono-openapi: ^1.2.0
    lucide-react: ^0.564.0
    pg: ^8.18.0
    postgres: ^3.4.8
    radix-ui: ^1.4.3
    react: ^19.2.0
    react-dom: ^19.2.0
    react-hook-form: ^7.71.1
    shadcn: ^3.8.4
    sonner: ^2.0.7
    tailwind-merge: ^3.4.1
    tailwindcss: ^4.1.18
    tsx: ^4.7.1
    tw-animate-css: ^1.4.0
    typescript: ^5.8.3
    typescript-eslint: ^8.48.0
    uuid: ^13.0.0
    vercel: ^50.19.1
    vite: ^7.3.1
    zod: ^4.3.6
    zod-openapi: ^5.4.6
    zod-to-json-schema: ^3.25.1
    zustand: ^5.0.11
    openapi-typescript: ^7.0.0
    openapi-fetch: ^0.13.0